from django.urls import path, include
from rest_framework.routers import DefaultRouter
from eco_backend.views import ProductViewSet # Assumes you have a ProductViewSet in views.py

# Django Rest Framework's DefaultRouter automatically generates the URLs for a ViewSet.
# This will create routes for list, create, retrieve, update, and destroy actions.
router = DefaultRouter()
router.register(r'products', ProductViewSet, basename='product')

# The urlpatterns list routes URLs to views.
urlpatterns = [
    # This includes all the URLs generated by the router.
    # It will create endpoints like:
    # /api/products/ -> for listing all products (GET) and creating a new one (POST)
    # /api/products/{id}/ -> for retrieving (GET), updating (PUT/PATCH), and deleting (DELETE) a single product.
    path('', include(router.urls)),

    # You might add other app-specific URLs here, for example, to list categories.
    # path('categories/', CategoryListView.as_view(), name='category-list'),
]